### ISSUE TITLE
Tensor Net For CIFAR-10

### ISSUE THREAD

**Issue by antra1608** [Bihaqo/TensorNet#6]
Hello sir,
Have you developed tensornet for CIFAR-10 dataset?
I am following your libraries for developing them. If you have implemented it would be nice for me to get some idea about it.

**Comment by huwade** [comment]
I think you can find it on there Tensorflow implement

**Comment by Bihaqo** [comment]
Hi @antra1608,

@huwade is absolutely right, check out the [Tensorflow version of the Cifar experiment](https://github.com/timgaripov/TensorNet-TF/tree/master/experiments/cifar-10/FC-Tensorizing-Neural-Networks). If you use Matlab, I can try to find the original Matlab code as well.
